---
- name: Config_Pull
  hosts: juniper_devices
  gather_facts: false

  tasks:
    - name: Get config
      ansible.netcommon.cli_command:
        command: show configuration
      register: output

    - name: Print Version
      debug:
        var: output.stdout_lines
