---
- name: Config_Pull
  hosts: juniper_devices
  gather_facts: false

  tasks:
    - name: Get config
      junipernetworks.junos.junos_command:
        commands: show configuration
      register: output

    - name: Print Version
      debug:
        var: output.stdout_lines
